import { Manrope } from "next/font/google";
import { Russo_One } from "next/font/google";
import { Archivo } from "next/font/google";
import { Farro } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Whatsapp from "@/components/Whatsapp";


const manrope = Manrope({ subsets: ["latin"] });
const russo = Russo_One({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-russo",
});
const archivo = Archivo({
  subsets: ["latin"],
  weight: "600",
  variable: "--font-archivo",
});
const farro = Farro({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-farro",
});

export const metadata = {
  title: "Quadruple",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${manrope.className} ${russo.variable} ${archivo.variable} ${farro.variable} text-darkgray`}
      >
        <Header/>
        {children}
        <Whatsapp/>
      </body>
    </html>
  );
}
